### ISSUE TITLE
Fix User SignUp

### ISSUE THREAD

**Issue by amanpatel123** [HarshdipD/share-the-ride#5]
Currently on sign up page confirm password blank can be blank (is not mandatory to fill). I believe it will be much better if we can make it mandatory to fill that blank. 

Also, I tried creating a user with password "test1234" and in place where it says confirm password I filled "test12". Strange but it allows me to create a user even though password and confirm password do not match. This can be a serious issue.

![image](https://user-images.githubusercontent.com/46072181/60392441-8bbff900-9ad0-11e9-914b-147b12c635af.png)

**Comment by HarshdipD** [comment]
Thanks for catching that. Try making changes in the `app/models/user.rb` and see if it works. Remember we need a separate branch for each issue and only one issue should be handled in that branch.

**Comment by amanpatel123** [comment]
Okay got it !

**Comment by amanpatel123** [comment]
I think I made this thing working but there is still one issue withe the css. The css of confirm password box changes for some reason. Do you have any idea why?

![abc](https://user-images.githubusercontent.com/46072181/60511086-2110e800-9c9f-11e9-808e-542d86486d34.jpg)

**Comment by HarshdipD** [comment]
It should work because the CSS is the same for all the input fields. Hopefully, this might be because of the cache in your browser. Try clearing it and see if it works.

**Comment by HarshdipD** [comment]
Closing this since the logic works now. Feel free to reopen if needed.
